function [fitresult, gof] = createFit
%CREATEFIT
%  Create a fit.
%
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 23-Mar-2020 14:38:20


%% Fit: 'untitled fit 1'.
% Cannot generate code for fit 'untitled fit 1' because the data selection is incomplete.


